# Generated by Django 5.2.4 on 2025-07-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('driver_number', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('headshot_url', models.URLField()),
                ('last_name', models.CharField(max_length=100)),
                ('meeting_key', models.IntegerField()),
                ('name_acronym', models.CharField(max_length=100)),
                ('session_key', models.IntegerField()),
                ('team_color', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Drivers',
                'ordering': ['last_name', 'first_name', 'driver_number'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_key', models.IntegerField()),
                ('circuit_short_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=100)),
                ('country_key', models.IntegerField()),
                ('country_name', models.CharField(max_length=100)),
                ('date_start', models.CharField(max_length=50)),
                ('gmt_offset', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('meeting_key', models.IntegerField()),
                ('meeting_name', models.CharField(max_length=100)),
                ('meeting_official_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Meetings',
                'ordering': ['meeting_name', 'year', 'meeting_key'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnf', models.BooleanField()),
                ('dns', models.BooleanField()),
                ('dsq', models.BooleanField()),
                ('driver_number', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('gap_to_leader', models.IntegerField()),
                ('number_of_laps', models.IntegerField()),
                ('meeting_key', models.IntegerField()),
                ('position', models.IntegerField()),
                ('session_key', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Results',
                'ordering': ['meeting_key', 'position', 'driver_number'],
            },
        ),
    ]
