# Generated by Django 5.2.4 on 2025-07-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='country',
            new_name='country_code',
        ),
    ]
