# Generated by Django 5.2.4 on 2025-07-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_rename_team_color_driver_team_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='country_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
