# Generated by Django 5.2.4 on 2025-07-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_meeting_meeting_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('points', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('season', models.CharField(max_length=5)),
                ('round', models.IntegerField()),
                ('driver_number', models.IntegerField()),
            ],
        ),
    ]
