# Generated by Django 5.2.4 on 2025-07-16 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_rename_country_driver_country_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='team_color',
            new_name='team_colour',
        ),
    ]
