# Generated by Django 5.2.4 on 2025-07-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_alter_driver_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='headshot_url',
            field=models.URLField(null=True),
        ),
    ]
