# Generated by Django 5.2.4 on 2025-07-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_alter_driver_headshot_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
