# Generated by Django 5.2.4 on 2025-09-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constructor_id', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Constructors',
                'ordering': ['name', 'constructor_id'],
            },
        ),
    ]
